### ISSUE TITLE
Charts rework

### ISSUE THREAD

**Issue by floribe2000** [WoWs-Builder-Team/WoWs-ShipBuilder#194]
Rewrite existing charts components to improve code readability, maintainability and performance and make supporting new features possible.

---

- [x] Rework ship and shell selection logic for ballistic charts: support builds and multiple ships of the same type
- [x] Ballistic charts should only use one unified dialog for ship and shell selection, even when coming from the main page
- [x] Add build configuration for shell selection dialog

---

## Tasks for later:

- Port new features to desktop
- Rework desktop charts
