### ISSUE TITLE
Rework Dispersion and Ballistic Charts

### ISSUE THREAD

**Issue by floribe2000** [WoWs-Builder-Team/WoWs-ShipBuilder#253]
Tracks various issues related to the chart rework
```[tasklist]
### Tasks
- [ ] https://github.com/WoWs-Builder-Team/WoWs-ShipBuilder/issues/264
- [ ] https://github.com/WoWs-Builder-Team/WoWs-ShipBuilder/issues/265
- [ ] https://github.com/WoWs-Builder-Team/WoWs-ShipBuilder/issues/266
- [ ] https://github.com/WoWs-Builder-Team/WoWs-ShipBuilder/issues/267
```
